name: Workflow inicial demo Caixa

on:
  workflow_dispatch:

jobs:
  greet:
    env:
      MY_ENV: "Priscila Ferreira"
    runs-on: ubuntu-latest
    steps:
      - name: saudacao ao usuario
        run: echo "Olá mundo"
      - run: ls -l
      - uses: actions/checkout@v6
      - run: ls -l
      - name: Execução de um script multi linha
        run:  |
          echo "Olá $MY_ENV"
          echo "Olá $GITHUB_ACTOR"
